### ISSUE TITLE
find bug of kinematics.html

### ISSUE THREAD

**Issue by borninfreedom** [CRH380B-6216L/ur5_webgui#2]
In the /ur5_webgui/webgui/www/kinematics.html, the first line code was wrote as '<script type="text/javascript" src="/ur5_rosgui/js/kinematics.js"></script>', 
![image](https://user-images.githubusercontent.com/48934506/87771132-899f1880-c852-11ea-89ba-2fdf6bb826a4.png)

but there is not a package named 'ur5_rosgui', shoud it be 'ur5_webgui' ?

**Comment by CRH380B-6216L** [comment]
fixed✅
